export const notifications = [
    {
        id: 1,
        section: "Today",
        user: "john_doe",
        message: "liked your photo.",
        time: "2m",
        avatar: "./assets/users/user-1.png",
        thumbnail: "./assets/users/user-1.png",
    },
    {
        id: 2,
        section: "Today",
        user: "sarah_wilson",
        message: 'commented: "Amazing shot! 🔥"',
        time: "5m",
        avatar: "./assets/users/user-1.png",
        thumbnail: "./assets/users/user-1.png",
    },
    {
        id: 3,
        section: "Today",
        user: "emma_jones",
        message: "liked your photo.",
        time: "1h",
        avatar: "./assets/users/user-1.png",
        thumbnail: "./assets/users/user-1.png",
    },
    {
        id: 4,
        section: "Yesterday",
        user: "lisa_travel",
        message: "liked your story.",
        time: "1d",
        avatar: "./assets/users/user-1.png",
        thumbnail: "./assets/users/user-1.png",
    },
    {
        id: 5,
        section: "Yesterday",
        user: "anna_fitness",
        message: 'replied to your comment: "Thanks for the tip!"',
        time: "1d",
        avatar: "./assets/users/user-1.png",
        thumbnail: "./assets/users/user-1.png",
    },
    {
        id: 6,
        section: "This Week",
        user: "tom_artist",
        message: "and 3 others commented on your photo.",
        time: "3d",
        avatar: "./assets/users/user-1.png",
        thumbnail: "./assets/users/user-1.png",
    },
    {
        id: 7,
        section: "This Week",
        user: "maria_design",
        message: 'liked your comment: "Love this aesthetic!"',
        time: "6d",
        avatar: "./assets/users/user-1.png",
        thumbnail: "./assets/users/user-1.png",
    },
];
